@startuml
'https://plantuml.com/class-diagram

class RentalService
class RentalRecord{
- String rentalObejct
- BigDecimal rentalPrice
- List<Integer> duration
- int numberAvailable
- int numberTotal
}
class RentalRepository
class RentalController
class BookingService
class BookingRecord{
- Rental rental
- int durationBooked
- BigDecimal totalCost
-
}
class BookingRepository
class BookingController



@enduml